### PR TITLE
Expose storage config request

### PR DESCRIPTION
**Pull request by WillSnowdon**
I'd like to make the storage config available via SDK method so it can be used to get useful info such as `shadesPerGiB` to help correctly calculate price estimates & how much $SHDW is needed when auto-swapping with other SPL tokens etc

### CODE REVIEW

**Comment by khaIilnafis** [comment]
Will need you to update your branch with the latest in master before going ahead with this

**Comment by WillSnowdon** [comment]
Didn't realise I hadn't, apologies.

**Comment by WillSnowdon** [comment]
If I remove the ordering of imports that my Editor did  - is there any more chance of having this merged?

**Comment by khaIilnafis** [comment]
Yep once that's cleaned up we'll get it merged

**Comment by khaIilnafis** [comment]
Are you actually looking for the storage config account or are you interested in storage accounts?

**Comment by WillSnowdon** [comment]
Storage config account, specifically for current value of `shadesPerGib` rather than having it hard coded.

Great, I'll remove the import re-ordering when I'm done with work. :)

**Review by NostalgicGareth — APPROVED** [review]

**Review by NostalgicGareth — APPROVED** [review]
- [ ]

**Review by NostalgicGareth — APPROVED** [review]
- [ ]

**Review by LeonAlvarez — APPROVED** [review]

**Comment by WillSnowdon** [comment]
Forget it lol

**Pull request closed without merging**
